# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular CI CD 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2.6.0
      
      
  #  - name: AWS Configuration
  #    uses: aws-actions/configure-aws-credentials@v1
  #    with:
  #      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #      aws-secret-key-access: ${{ secrets.AWS_SECRET_KEY_ACCESS }}
  #      aws-region: eu-central-1
        
    
    - name: Set Up Node Js
      uses: actions/setup-node@v3.5.1
      
      
    - name: Installing Anguler
      run: npm i @angular/cli
      
    - name: Creating Build with Angular
      run: ng build
      
    
    
      
    
      
    
      
      
      
      
      
      
      
      
      
      
